@url = http://localhost:3001/api
@json = Content-Type: application/json

### Test the root endpoint

GET {{url}}

### Test the register endpoint

POST {{url}}/register
{{json}}

{
    "username": "user3",
    "password": "123456"
}

### Test the get all users endpoint

GET {{url}}/users

### Test the login endpoint

POST {{url}}/login
{{json}}

{
    "username": "user2",
    "password": "123456"
}


### Test the profile endpoint
# This request fetches the user's profile
# It requires authentication using a JWT token

GET {{url}}/profile
# The Authorization header includes the Bearer token for authentication
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYwZWQ5NGMyMTMxODkxNWIxNWExNGEiLCJpYXQiOjE3MjcxNDEzNTZ9.tnq7GeCE_t54BdWLzie8rBfDS6-BGoRqzWIwM2lWqxc